### ISSUE TITLE
Feature #1 : User can add a plant on their “My Plants” list

### ISSUE THREAD

**Issue by patriciamanalang** [patriciamanalang/plant-diary#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a plant on their “My Plants” list that they would like to start tracking development

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once logged in, the user will be taken to the app's **home page** which is a form where --- User can enter a plant name + click a button that says "Add To My Plants". After clicking that button,
The user will then be taken to a new page that lists the plants they are tracking.

If the user has no plants on their plant list and they click on the plant icon on the nav bar, the page will say "You have no plants on your plant list!" with a button that says "Add a plant". When the user clicks that button, they will be taken to the home page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-29 at 9 01 37 AM](https://user-images.githubusercontent.com/109925604/209985313-61df6335-f6ca-46fe-b313-1a480a1ebda2.png)
![Screen Shot 2022-12-29 at 9 01 13 AM](https://user-images.githubusercontent.com/109925604/209985323-1c4c595f-b435-4ce6-9d25-c4a9e13b3932.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create a plants entries table
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a post request to add a plant on "My plants" list
- [x] Test with HTTPie by sending a POST request to the server localhost:3000/api/plantdiary
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for the "Add a plant" page
- [x] Update component to send a fetch request when submitting to post the entered plant name to the database

- [x] add <input> element for plant name with labels, type & placeholder
- [x] add <textarea> element
- [x] make sure they are all required
- [x] make sure they all have the appropriate 'type' , 'name' , 'value' , etc.
- [x] Define a handleChange method:
- [x] use 'setState()' to update the state of all inputs
- [x] Define a handleSubmit method:
- [x] prevent the default form submission behavior
- [x] use 'fetch()' to send a POST request to /api/plantentries
- [x] use form data object as the body
- [x] headers are not needed
- [x] parse the response body
- [x] reset all form inputs
- [x] catch any errors
- [x] Verify that new plant entries are saved to the database when the form is submitted
- [x] Verify that each new entry receives an incrementing entryId
- [x] Bind handleSubmit and handleChange
- [x] Update the App component to render and mount form
- [x] Ensure that the form looks nice on both mobile and desktop

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
