### ISSUE TITLE
Feature #2 : User can view a list of the plants they are currently tracking

### ISSUE THREAD

**Issue by patriciamanalang** [patriciamanalang/plant-diary#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
Once the user adds a plant, the plant will show up in their "My Plants" list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view a list of the plants they are currently tracking 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-28 at 10 53 07 AM](https://user-images.githubusercontent.com/109925604/209859223-666af751-3b77-42d7-bb81-39a57e634de7.png)
![Screen Shot 2022-12-28 at 10 53 20 AM](https://user-images.githubusercontent.com/109925604/209859232-a11282ff-e590-43ed-b955-50202eba7e7b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle GET requests
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to view "My Plants" list
- [x] Update My Plants component to display user plant collections upon click

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
