### ISSUE TITLE
Feature #3 : User can remove a plant from their “‘My Plants” list

### ISSUE THREAD

**Issue by patriciamanalang** [patriciamanalang/plant-diary#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can delete from their “‘My Plants” list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will be able to remove an entire plant from their "My Plants" list along with all the entries related to that plant.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-28 at 11 19 25 AM](https://user-images.githubusercontent.com/109925604/209861939-c9b141d7-ba21-49eb-8e06-e536cee98c3a.png)
![Screen Shot 2022-12-28 at 11 19 43 AM](https://user-images.githubusercontent.com/109925604/209861947-aa65a13f-c144-4a87-bbe8-ddcf505c471a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...
- [x] Create a DELETE route

### ☁️ Server Tasks

- [x] Update `server/index.js` to delete a plant from "My Plants" list
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ... Create Delete modal
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
